// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenLU.DBContext;

namespace OpenLU.DBContext.Migrations.Base
{
    [DbContext(typeof(BaseContext))]
    [Migration("20201111194539_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("OpenLU.Models.GameModels+Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Eyebrows")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Eyes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FreeToPlay")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HairColor")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HairStyle")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Head")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HeadColor")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LH")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LastLogin")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LastMapClone")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("LastMapInstance")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Mouth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PantsColor")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PantsStyle")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RH")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ShirtColor")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ShirtStyle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Zone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Equipped")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Lot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentCharId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Password")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentCharId = 0L,
                            Password = "lego!",
                            Username = "MrSnrub"
                        });
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+Character", b =>
                {
                    b.HasOne("OpenLU.Models.GameModels+User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+InventoryItem", b =>
                {
                    b.HasOne("OpenLU.Models.GameModels+Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
