// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenLU.DBContext;

namespace OpenLU.DBContext.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20200819205541_CharUpdate")]
    partial class CharUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OpenLU.Models.GameModels+Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Eyebrows")
                        .HasColumnType("int");

                    b.Property<int>("Eyes")
                        .HasColumnType("int");

                    b.Property<bool>("FreeToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HairStyle")
                        .HasColumnType("int");

                    b.Property<int>("LH")
                        .HasColumnType("int");

                    b.Property<int>("LastMapClone")
                        .HasColumnType("int");

                    b.Property<int>("LastMapInstance")
                        .HasColumnType("int");

                    b.Property<int>("Mouth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PantsColor")
                        .HasColumnType("int");

                    b.Property<int>("PantsStyle")
                        .HasColumnType("int");

                    b.Property<int>("RH")
                        .HasColumnType("int");

                    b.Property<int>("ShirtColor")
                        .HasColumnType("int");

                    b.Property<int>("ShirtStyle")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Password")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+Character", b =>
                {
                    b.HasOne("OpenLU.Models.GameModels+User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
