// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenLU.DBContext;

namespace OpenLU.DBContext.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20201104204202_04112020")]
    partial class _04112020
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OpenLU.Models.GameModels+Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint>("Eyebrows")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Eyes")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("FreeToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("HairColor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HairStyle")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LH")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("LastLogin")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("LastMapClone")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("LastMapInstance")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Mouth")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint>("PantsColor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("PantsStyle")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RH")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ShirtColor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ShirtStyle")
                        .HasColumnType("int unsigned");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Password")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenLU.Models.GameModels+Character", b =>
                {
                    b.HasOne("OpenLU.Models.GameModels+User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
