using System;
using System.Collections.Generic;

namespace OpenLU.DBContext.Client
{
    public partial class VehiclePhysics
    {
        public long? Id { get; set; }
        public string HkxFilename { get; set; }
        public double? FGravityScale { get; set; }
        public double? FMass { get; set; }
        public double? FChassisFriction { get; set; }
        public double? FMaxSpeed { get; set; }
        public double? FEngineTorque { get; set; }
        public double? FBrakeFrontTorque { get; set; }
        public double? FBrakeRearTorque { get; set; }
        public double? FBrakeMinInputToBlock { get; set; }
        public double? FBrakeMinTimeToBlock { get; set; }
        public double? FSteeringMaxAngle { get; set; }
        public double? FSteeringSpeedLimitForMaxAngle { get; set; }
        public double? FSteeringMinAngle { get; set; }
        public double? FFwdBias { get; set; }
        public double? FFrontTireFriction { get; set; }
        public double? FRearTireFriction { get; set; }
        public double? FFrontTireFrictionSlide { get; set; }
        public double? FRearTireFrictionSlide { get; set; }
        public double? FFrontTireSlipAngle { get; set; }
        public double? FRearTireSlipAngle { get; set; }
        public double? FWheelWidth { get; set; }
        public double? FWheelRadius { get; set; }
        public double? FWheelMass { get; set; }
        public double? FReorientPitchStrength { get; set; }
        public double? FReorientRollStrength { get; set; }
        public double? FSuspensionLength { get; set; }
        public double? FSuspensionStrength { get; set; }
        public double? FSuspensionDampingCompression { get; set; }
        public double? FSuspensionDampingRelaxation { get; set; }
        public long? IChassisCollisionGroup { get; set; }
        public double? FNormalSpinDamping { get; set; }
        public double? FCollisionSpinDamping { get; set; }
        public double? FCollisionThreshold { get; set; }
        public double? FTorqueRollFactor { get; set; }
        public double? FTorquePitchFactor { get; set; }
        public double? FTorqueYawFactor { get; set; }
        public double? FInertiaRoll { get; set; }
        public double? FInertiaPitch { get; set; }
        public double? FInertiaYaw { get; set; }
        public double? FExtraTorqueFactor { get; set; }
        public double? FCenterOfMassFwd { get; set; }
        public double? FCenterOfMassUp { get; set; }
        public double? FCenterOfMassRight { get; set; }
        public double? FWheelHardpointFrontFwd { get; set; }
        public double? FWheelHardpointFrontUp { get; set; }
        public double? FWheelHardpointFrontRight { get; set; }
        public double? FWheelHardpointRearFwd { get; set; }
        public double? FWheelHardpointRearUp { get; set; }
        public double? FWheelHardpointRearRight { get; set; }
        public double? FInputTurnSpeed { get; set; }
        public double? FInputDeadTurnBackSpeed { get; set; }
        public double? FInputAccelSpeed { get; set; }
        public double? FInputDeadAccelDownSpeed { get; set; }
        public double? FInputDecelSpeed { get; set; }
        public double? FInputDeadDecelDownSpeed { get; set; }
        public double? FInputSlopeChangePointX { get; set; }
        public double? FInputInitialSlope { get; set; }
        public double? FInputDeadZone { get; set; }
        public double? FAeroAirDensity { get; set; }
        public double? FAeroFrontalArea { get; set; }
        public double? FAeroDragCoefficient { get; set; }
        public double? FAeroLiftCoefficient { get; set; }
        public double? FAeroExtraGravity { get; set; }
        public double? FBoostTopSpeed { get; set; }
        public double? FBoostCostPerSecond { get; set; }
        public double? FBoostAccelerateChange { get; set; }
        public double? FBoostDampingChange { get; set; }
        public double? FPowerslideNeutralAngle { get; set; }
        public double? FPowerslideTorqueStrength { get; set; }
        public long? IPowerslideNumTorqueApplications { get; set; }
        public double? FImaginationTankSize { get; set; }
        public double? FSkillCost { get; set; }
        public double? FWreckSpeedBase { get; set; }
        public double? FWreckSpeedPercent { get; set; }
        public double? FWreckMinAngle { get; set; }
        public string AudioEventEngine { get; set; }
        public string AudioEventSkid { get; set; }
        public string AudioEventLightHit { get; set; }
        public double? AudioSpeedThresholdLightHit { get; set; }
        public double? AudioTimeoutLightHit { get; set; }
        public string AudioEventHeavyHit { get; set; }
        public double? AudioSpeedThresholdHeavyHit { get; set; }
        public double? AudioTimeoutHeavyHit { get; set; }
        public string AudioEventStart { get; set; }
        public string AudioEventTreadConcrete { get; set; }
        public string AudioEventTreadSand { get; set; }
        public string AudioEventTreadWood { get; set; }
        public string AudioEventTreadDirt { get; set; }
        public string AudioEventTreadPlastic { get; set; }
        public string AudioEventTreadGrass { get; set; }
        public string AudioEventTreadGravel { get; set; }
        public string AudioEventTreadMud { get; set; }
        public string AudioEventTreadWater { get; set; }
        public string AudioEventTreadSnow { get; set; }
        public string AudioEventTreadIce { get; set; }
        public string AudioEventTreadMetal { get; set; }
        public string AudioEventTreadLeaves { get; set; }
        public string AudioEventLightLand { get; set; }
        public double? AudioAirtimeForLightLand { get; set; }
        public string AudioEventHeavyLand { get; set; }
        public double? AudioAirtimeForHeavyLand { get; set; }
        public long? BWheelsVisible { get; set; }
    }
}
